class_name GameEnums
extends RefCounted

## Central namespace for shared enum vocabulary used across the game's systems.
## Kept as a single static reference (no instances, no autoload) so every
## script speaks the same terms without cross-importing each other directly.

enum BiomeType {
	URBAN,        ## City streets / settlement footprint.
	INDUSTRIAL,   ## Slag heaps, mine spoil, blighted factory ground.
	FARMLAND,     ## Open, tillable countryside (fertility varies, see SoilFertility).
	MOORLAND,     ## Open, less fertile countryside.
	HIGHLAND,     ## Elevated terrain / mountain chains (Pennines, Chilterns, Cotswolds).
	WATERWAY,     ## River or canal hex.
	WETLAND,      ## Marsh, fen or peat bog.
}

enum SoilFertility {
	LUSH,        ## Prime farmland (e.g. Cheshire Plain, Midlands).
	POOR,        ## Marginal farmland (e.g. moorland fringe).
	DESOLATE,    ## Industrial blight or drained wetland; barely arable.
	NOT_ARABLE,  ## Urban, open water, etc. — farming is not applicable here.
}

enum DistrictType {
	URBAN_CENTER,          ## Civilian core: Town Halls, Churches, Telegraph Relays.
	INDUSTRIAL_ESTATE,     ## Production core: foundries, mills, workshops.
	UNCLEARED_WILDERNESS,  ## Contested ground; active zombie presence until cleared.
}

enum TerrainFeature {
	NONE,
	RIVER,
	CANAL,
	MARSH,
	PEAT_BOG,
	ESCARPMENT,  ## Mountain / hill chokepoint terrain.
}

enum CameraPerspective {
	TOP_DOWN,
	ISOMETRIC,
}

enum ResourceType {
	FOOD,                   ## Population upkeep drain.
	ENERGY,                 ## Coal, Gas, Oil used for Boiler/heating/streetlamp upkeep.
	GUNPOWDER,              ## Ranged combat & garrison upkeep.
	RESEARCH_POINTS,        ## Tech Tree progression currency (Phase 2.9) — generated by civic/knowledge buildings, spent by TechManager.
	WOOD,                   ## Construction material.
	BRICKS,                 ## Construction material.
	CAST_IRON,              ## Construction material.
	REINFORCED_CONCRETE,    ## Construction material — no Phase 2 building produces this yet.
}

enum BuildingCategory {
	HOUSING_CIVIL,       ## Terraced Tenements, Workhouses, Watchtowers, etc.
	INDUSTRY_EXTRACTION, ## Brickworks, kilns, pitheads, foundries, powder mills, ammo dumps.
	AGRICULTURE,         ## Tenant Farms, Grain Silos, Cattle Yards.
	DEFENSE_WORKS,       ## Phase 4.1: Searchlight Tower (a normal hex-placed building), plus Ditch/Oil Pit's cost data (placed via WallManager, not BuildingManager — see WallManager's own doc comment).
}

enum BuildingType {
	# --- Housing & Civil ---
	TERRACED_TENEMENT,
	WORKHOUSE,
	CHURCH_STEEPLE_WATCHTOWER,
	GAS_STREETLAMP,
	TELEGRAPH_RELAY_OFFICE,
	STEAM_PRINTING_PRESS,
	TOWN_HALL,   ## Not in the Phase 2.1 checklist by name, but required as a Civilian ZoC
	GARRISON,    ## projector by 2.3; added here as the civic-seat/militia-HQ pairing for it.
	# --- Industry & Extraction ---
	CLAY_BRICKWORKS,
	CHARCOAL_KILN,
	COAL_PITHEAD,
	CAST_IRON_FOUNDRY,
	SALTPETRE_POWDER_MILL,
	FORWARD_AMMO_DUMP,
	# --- Agriculture ---
	TENANT_FARM,
	GRAIN_SILO,
	CATTLE_YARD,
	# --- Defense Works (Phase 4.1) ---
	SEARCHLIGHT_TOWER,  ## Normal hex-placed building (BuildingManager), like Gas Streetlamp.
	DITCH,              ## Cost data only — placed via WallManager.add_defense_work(), attached to a specific WallSegment.
	OIL_PIT,            ## Cost data only — same as DITCH.
}

## Design doc Phase 5.4: 3 roles per unit tier. Melee/ranged are
## self-explanatory; special's "exact combat identity per tier (area-effect,
## heavy-breach, mobility/scouting, etc.) is a balancing/design pass per
## unit, not fixed by this spec" (design doc, decided) — UnitCatalog gives
## each special-role unit a plausible baseline, not a final tuned identity.
enum UnitRole {
	MELEE,
	RANGED,
	SPECIAL,
}

## Design doc Phase 5.4's decided roster — 6 tiers (0-5) x 3 roles = 18
## units. Declared tier-by-tier, melee/ranged/special within each tier, same
## grouped-comment convention BuildingType uses.
enum UnitType {
	# --- Tier 0 (the "Free Ammo" starting tier, no tech needed) ---
	TRUNCHEONEER,           ## Melee.
	TOXOPHILITE,            ## Ranged — bow; no Gunpowder upkeep, exempt from the depletion penalty by design.
	OUTRIDER,               ## Special — scouting/mobility.
	# --- Tier 1 (unit_tier_1) ---
	NAVVY,                  ## Melee.
	YEOMAN_MARKSMAN,        ## Ranged — the first firearm-era ranged unit; Gunpowder depletion penalty starts here.
	GRENADIER,              ## Special.
	# --- Tier 2 (unit_tier_2) ---
	REDCOAT,                ## Melee.
	RIFLEMAN,               ## Ranged.
	CHASSEUR,               ## Special.
	# --- Tier 3 (unit_tier_3) ---
	HIGHLANDER,             ## Melee.
	SHARPSHOOTER,           ## Ranged.
	DRAGOON,                ## Special.
	# --- Tier 4 (unit_tier_4) — grounded heavy engineering, not battle-mechs (design doc, decided). ---
	STEAM_PRAM_RAMMER,      ## Melee.
	ARMORED_LOCOMOTIVE_GUNNER,  ## Ranged.
	STEAM_TRACTOR_LANDSHIP, ## Special.
	# --- Tier 5 (unit_tier_5) — same "no retro-futuristic steampunk tropes" rule as Tier 4. ---
	STEAM_MACHINE_LEG,      ## Melee.
	RAILWAY_SIEGE_HOWITZER, ## Ranged.
	WAR_MACHINE_ARMORED_CAR,  ## Special.
}

## Design doc Phase 5.6's "standard RTS order set" — what a UnitInstance is
## currently doing, driven by UnitOrderController. HOLD is the default (a
## freshly-trained unit with no rally point set just sits at its training
## building). ATTACK_MOVE is data-distinct from MOVE (a future engage-on-
## contact behavior can tell them apart) but currently drives identically —
## UnitOrderController doesn't yet trigger combat on contact with a horde;
## see that class's own doc comment for why (no reviewed horde-combat-stat
## decision exists yet, Horde.size is a headcount, not a combat stat).
enum UnitOrderType {
	HOLD,         ## Stand fast at the current hex — the default.
	MOVE,         ## Path to move_target, one hex per movement tick, then reverts to HOLD on arrival.
	ATTACK_MOVE,  ## Same movement as MOVE; the "attack" half (engage anything encountered en route) isn't wired yet.
	PATROL,       ## Loop through patrol_waypoints indefinitely, one leg at a time.
	GARRISON,     ## Stand fast at the current hex, same as HOLD — the "stationary defense bonus" (design doc) isn't wired yet, needs Phase 5.4's combat stats to bonus something that doesn't exist yet either.
}

enum ZoneOfControlType {
	MILITARY,   ## Forward Ammo Dumps, Garrisons, Watchtowers, Combat Units.
	CIVILIAN,   ## Town Halls, Churches (the Watchtower's civilian half), Telegraph Relays.
}

enum SupplyLineType {
	ROAD,
	RAILWAY,
	CANAL,
}

enum PropType {
	TREE,
	BUSH,
	ROCK,
	REED,  ## Wetland/waterway fringe vegetation.
}

enum FogState {
	UNSEEN,    ## Never scouted; rendered as blank darkness. One-way -> EXPLORED, never reverts.
	EXPLORED,  ## Terrain/buildings remembered, no current intel on movement in this hex.
	VISIBLE,   ## An active vision source covers this hex right now; full real-time information.
}

enum DayPhase {
	DAY,    ## First half of TickManager's day cycle — baseline vision, no zombie/unit modifiers wired yet (Phase 5.2/5.4 don't exist).
	NIGHT,  ## Second half — drives FogOfWarManager's vision contraction (Phase 2.6.4); zombie/unit modifiers deferred the same way.
}

enum HordeState {
	WANDERING,  ## Default (design doc Phase 5.10) — drifts across passable uncleared wilderness, no deliberate target. The only state HordeManager actually produces right now.
	ATTRACTED,  ## Pathing deliberately toward a noise/light source above threshold. Not yet produced — needs Phase 5.2's industrial-noise tracking, which doesn't exist yet.
	ATTACKING,  ## Besieging a specific wall segment/hex, handed off to combat. Not yet produced — needs Phase 5.4's CombatEngine, which doesn't exist yet.
}

enum TechUnlockType {
	WALL_TIER,        ## Unlocks a Phase 4.1 wall tier (unlock_value: 1=Brick, 2=Concrete; tier 0/Wooden is baseline, no tech needed).
	UNIT_TIER,        ## Unlocks a whole Phase 5.4 unit tier, all 3 roles at once (unlock_value: 1-5; tier 0 is baseline, no tech needed).
	BUILDING_VARIANT, ## Unlocks an advanced building variant — documented hook, unused until a variant building actually exists.
	SEAFARING,        ## The one node gated on campaign state as well as prerequisites — see TechDefinition.requires_wales_and_scotland_retaken.
}
