class_name GameEnums
extends RefCounted

## Central namespace for shared enum vocabulary used across the game's systems.
## Kept as a single static reference (no instances, no autoload) so every
## script speaks the same terms without cross-importing each other directly.

enum BiomeType {
	URBAN,        ## City streets / settlement footprint.
	INDUSTRIAL,   ## Slag heaps, mine spoil, blighted factory ground.
	FARMLAND,     ## Open, tillable countryside (fertility varies, see SoilFertility).
	MOORLAND,     ## Open, less fertile countryside.
	HIGHLAND,     ## Elevated terrain / mountain chains (Pennines, Chilterns, Cotswolds).
	WATERWAY,     ## River or canal hex — fordable, unlike open OCEAN below.
	WETLAND,      ## Marsh, fen or peat bog.
	OCEAN,        ## Open sea — impassable (HexCell.is_passable()) until Naval Logistics/ships exist; the map's own default base layer before BritishGeographyData's landmass stamp turns land hexes to MOORLAND.
	## WOODLAND/HEATHLAND carved out of what tools/geo_bake previously
	## flattened into MOORLAND — OSM landuse=forest/natural=wood (WOODLAND)
	## and natural=heath/natural=scrub (HEATHLAND) were already being
	## fetched and discarded into the same catch-all bucket as open grazing
	## land. Appended at the END of the enum, not inserted near MOORLAND/
	## WETLAND above — Godot enums serialize as raw int ordinals
	## (HexCell.biome_type, SaveLoadManager) and inserting mid-list would
	## silently shift OCEAN's ordinal and corrupt any existing save file.
	WOODLAND,     ## Dense tree cover — OSM landuse=forest / natural=wood.
	HEATHLAND,    ## Heather/gorse scrubland — OSM natural=heath / natural=scrub.
}

enum SoilFertility {
	LUSH,        ## Prime farmland (e.g. Cheshire Plain, Midlands).
	POOR,        ## Marginal farmland (e.g. moorland fringe).
	DESOLATE,    ## Industrial blight or drained wetland; barely arable.
	NOT_ARABLE,  ## Urban, open water, etc. — farming is not applicable here.
}

enum DistrictType {
	URBAN_CENTER,          ## Civilian core: Town Halls, Churches, Telegraph Relays.
	INDUSTRIAL_ESTATE,     ## Production core: foundries, mills, workshops.
	UNCLEARED_WILDERNESS,  ## Contested ground; active zombie presence until cleared.
}

enum TerrainFeature {
	NONE,
	RIVER,
	CANAL,
	MARSH,
	PEAT_BOG,
	ESCARPMENT,  ## Mountain / hill chokepoint terrain.
}

enum CameraPerspective {
	TOP_DOWN,
	ISOMETRIC,
}

## design_doc.md §2's "Streamlined Resource Pool": 6 raw, 5 processed, 4
## capacity/yield. Reordering this enum is a save-breaking change (values are
## stored as raw ordinals — ResourceManager/SaveGameData) but this rework
## already breaks old saves via the building/unit tree changes it unblocks,
## so ordinal stability isn't preserved here the way BiomeType's own doc
## comment insists on.
enum ResourceType {
	# --- Capacity & Yield Pools (4) ---
	FOOD,                ## Daily upkeep drawn by housed Population; low satisfaction cuts production (BuildingSustenanceController) rather than killing anyone.
	ENERGY,              ## Capacity pool: producers grant it once at construction, consumers reserve a flat share once at construction, both reversed on ruin/demolish (CapacityAllocator).
	POPULATION,          ## Capacity pool, same mechanics as ENERGY: housing grants it, non-housing buildings and units both reserve a flat share once (at construction / training), refunded on demolition/ruin/death (CapacityAllocator).
	RESEARCH_POINTS,     ## Tech Tree progression currency — generated by civic/knowledge buildings, spent by TechManager.
	# --- Raw Resources (6) ---
	WOOD,                ## Tier 0 — Lumber Yard/Timber Camp.
	CLAY,                ## Tier 0 — Clay Pit. Feeds Bricks.
	COAL,                ## Tier 1 — Coal Mine. Feeds Iron/Steel/Concrete/Gunpowder recipes and Coal Powerplants.
	LIMESTONE,           ## Tier 1 — Limestone Quarry. Feeds Concrete.
	IRON_ORE,            ## Tier 2 — Iron Ore Mine. Feeds Iron/Steel.
	SULFUR,              ## Tier 3 — Sulfur Mine. Feeds Gunpowder.
	# --- Processed Resources (5) ---
	BRICKS,              ## Brickworks (Clay).
	IRON,                ## Iron Foundry (Iron Ore, Coal). Was CAST_IRON — assets/icons/cast_iron.png keeps its old filename, see ResourceVisuals._icon_key().
	STEEL,               ## Steelworks/Bessemer Complex (Iron Ore or Iron, + Coal).
	CONCRETE,            ## Concrete Plant (Limestone, Clay, Coal). Was REINFORCED_CONCRETE.
	GUNPOWDER,           ## Gunpowder Mill/Synthetic Refinery (Sulfur, Coal). Ranged combat & garrison upkeep.
}

enum BuildingCategory {
	HOUSING_CIVIL,       ## Town Hall, Houses/Tower Blocks, Watchtower, Garrison/Armory/High Command/Traction Works/Ordnance (training buildings), Research Institute.
	INDUSTRY_EXTRACTION, ## Raw extraction, processed-resource production, power generation.
	AGRICULTURE,         ## Farms.
	DEFENSE_WORKS,       ## Search Light — the only BuildingCatalog entry left in this category; walls have their own WallCatalog tier system.
}

## design_doc.md §3's Tiered Building Specifications, grouped by tier (1
## group per tier, comments). Fully replaced from the pre-rework tree —
## design_doc.md's list is authoritative; buildings with no doc equivalent
## (Gas Streetlamp, Telegraph Relay Office, Steam Printing Press, Grain
## Silo, Cattle Yard, Ditch, Oil Pit) were cut rather than carried over.
## Ordinal stability isn't preserved (already broken by the resource
## rework; see ResourceType's own doc comment).
enum BuildingType {
	# --- Town Hall — pre-built free at game start; BuildingDefinition.tier
	# gates further construction to Tier 3, not this grouping ---
	TOWN_HALL,
	# --- Tier 0: Wood Base / Settlement ---
	LUMBER_YARD,
	CLAY_PIT,
	SMALLHOLDING_FARM,
	STEAM_FURNACE,
	WOODEN_HOUSES,
	WATCHTOWER,
	# --- Tier 1: Brick Base / Borough ---
	COAL_MINE,
	LIMESTONE_QUARRY,
	BRICKWORKS,
	ESTATE_FARM,
	COAL_POWERPLANT,
	RESEARCH_INSTITUTE,
	BRICK_HOUSES,
	GARRISON,
	SUPPLY_DUMP,
	# --- Tier 2: Iron Base / Industrial District ---
	IRON_ORE_MINE,
	IRON_FOUNDRY,
	CONCRETE_PLANT,
	INDUSTRIAL_FARM,
	TOWER_BLOCKS,
	ARMORY_AND_BARRACKS,
	SEARCH_LIGHT,
	# --- Tier 3: Steel Base / Rail Network ---
	SULFUR_MINE,
	DEEP_COAL_SHAFTS,  ## High-output Coal consolidator, added post-launch balance pass — see design_doc.md §3 Tier 3.
	SAWMILLS,          ## Same role for Wood.
	GUNPOWDER_MILL,
	STEELWORKS,
	MECHANISED_FARM,
	ADVANCED_COAL_POWERPLANT,
	HIGH_COMMAND_AND_CAVALRY_DEPOT,
	# --- Tier 4: Advanced Engineering / Automation & Maintenance Era ---
	STEAM_EXCAVATOR_DEPOT,
	HEAVY_COAL_WASHERY_AND_PULVERIZER,
	MECHANIZED_MAINTENANCE_DEPOT,
	MACADAMIZED_TRANSPORT_HUB,
	STEAM_TURBINE_POWER_PLANT,
	TRACTION_WORKS_AND_WORKSHOP,
	# --- Tier 5: Heavy Industrial / Super-Complex Era ---
	BESSEMER_SMELTING_COMPLEX,
	AUTOMATED_FREIGHT_MARSHALLING_YARD,
	SYNTHETIC_CHEMICAL_REFINERY,
	CENTRAL_HIGH_VOLTAGE_GRID_STATION,
	ORDNANCE_AND_ARMAMENT_COMPLEX,
}

## 3 roles per unit tier. Melee/ranged are self-explanatory; special's exact
## combat identity per tier (area-effect, heavy-breach, mobility/scouting,
## etc.) is a balancing/design pass per unit — UnitCatalog gives each
## special-role unit a plausible baseline, not a final tuned identity.
enum UnitRole {
	MELEE,
	RANGED,
	SPECIAL,
}

## A real, mechanical differentiator for every SPECIAL-role unit, not just
## flavor text. NONE covers every MELEE/RANGED unit (their differentiation
## is the existing tier/role HP-damage curve alone) and any SPECIAL unit
## that hasn't been given a distinct mechanic.
enum UnitAbility {
	NONE,
	UNARMED_SCOUT,       ## Outrider — cannot fight (near-zero attack_damage), fast mounted vision/recon only. See UnitCatalog.
	MOUNTED_FIREARM,     ## Chasseur — mounted AND actually armed, a real combat option unlike the Outrider it out-classes. See UnitCatalog.
	EXPLOSIVE_SPLASH,    ## Grenadier — grenades; expressed as a real damage bonus (a horde is already one clustered "blob" target, so splash reads as extra effectiveness against it). See UnitCatalog.
	CHARGE_KNOCKBACK,    ## Dragoon — charging into a horde on contact knocks it back a hex AND stuns it briefly. See CombatCoordinator._apply_special_ability_effects().
	TRAMPLE_KNOCKBACK,   ## Traction Ram AND Holt Breaker — same knockback as a Charge, no stun, riding on a much larger HP pool (a damage sponge that shoves zombies aside rather than a fast shock unit); shared by both because they're the same "crush the horde by weight" identity at two tiers. See CombatCoordinator._apply_special_ability_effects().
	MOBILE_SUPPLY_DUMP,  ## Searchlight Tender — projects a small Military ZoC/resupply aura around wherever it currently stands, like a walking (much-reduced-radius) Forward Ammo Dump; doubles as a moving vision source too (FogOfWarManager reads ZoC coverage as vision), which illuminates infected sectors. See LogisticsNetwork.recompute().
	RAPID_RESPONSE,      ## Armoured Command Car — fast and lightly armed rather than a heavy hitter: real speed/damage/HP leans (UnitCatalog), no bespoke effect code, same "pure stat lean under a descriptive name" shape as UNARMED_SCOUT/MOUNTED_FIREARM/EXPLOSIVE_SPLASH.
}

## 6 tiers (0-5) x 3 roles = 18 units. Declared tier-by-tier, melee/ranged/
## special within each tier, same grouped-comment convention BuildingType uses.
enum UnitType {
	# --- Tier 0 (the "Free Ammo" starting tier, no tech needed) ---
	TRUNCHEONEER,           ## Melee.
	TOXOPHILITE,            ## Ranged — bow; no Gunpowder upkeep, exempt from the depletion penalty by design.
	OUTRIDER,               ## Special — scouting/mobility.
	# --- Tier 1 (unit_tier_1) ---
	NAVVY,                  ## Melee.
	YEOMAN_MARKSMAN,        ## Ranged — the first firearm-era ranged unit; Gunpowder depletion penalty starts here.
	GRENADIER,              ## Special.
	# --- Tier 2 (unit_tier_2) ---
	BAYONETEER,             ## Melee.
	REDCOAT,                ## Ranged.
	CHASSEUR,               ## Special.
	# --- Tier 3 (unit_tier_3) ---
	HIGHLANDER,             ## Melee.
	SHARPSHOOTER,           ## Ranged.
	DRAGOON,                ## Special.
	# --- Tier 4 (unit_tier_4) — Early Mechanization & Heavy Logistics (1890s-1900s). ---
	TRACTION_RAM,           ## Melee.
	MAXIM_QUADRICYCLE,      ## Ranged.
	SEARCHLIGHT_TENDER,     ## Special.
	# --- Tier 5 (unit_tier_5) — Peak Industrial Warfare (1910s-1920s). ---
	HOLT_BREAKER,           ## Melee.
	FIELD_HOWITZER_GUN_TRACTOR,  ## Ranged.
	ARMOURED_COMMAND_CAR,   ## Special.
}

## The standard RTS order set — what a UnitInstance is currently doing,
## driven by UnitOrderController. HOLD is the default (a freshly-trained
## unit with no rally point set just sits at its training building).
## ATTACK_MOVE is data-distinct from MOVE, but drives identically —
## CombatCoordinator engages a horde on contact regardless of a unit's
## current order, so there's no distinct "attack" behavior left for this
## value to carry beyond intent-tracking. See CombatCoordinator's own doc comment.
enum UnitOrderType {
	HOLD,         ## Stand fast at the current hex — the default.
	MOVE,         ## Path to move_target, one hex per movement tick, then reverts to HOLD on arrival.
	ATTACK_MOVE,  ## Same movement AND same on-contact engagement as MOVE — see this enum's own doc comment.
	PATROL,       ## Loop through patrol_waypoints indefinitely, one leg at a time.
	GARRISON,     ## Stand fast at the current hex, same as HOLD, but with two real payoffs HOLD doesn't get: UnitOrderController._regen_if_friendly()'s healing and CombatCoordinator._garrison_incoming_multiplier()'s incoming-damage reduction, stacking further at night near a Searchlight Tower.
}

enum ZoneOfControlType {
	MILITARY,   ## Forward Ammo Dumps, Garrisons, Watchtowers, Combat Units.
	CIVILIAN,   ## Town Halls, Churches (the Watchtower's civilian half), Telegraph Relays.
}

enum SupplyLineType {
	ROAD,
	RAILWAY,
	CANAL,
}

enum PropType {
	TREE,
	BUSH,
	ROCK,
	REED,  ## Wetland/waterway fringe vegetation.
}

enum FogState {
	UNSEEN,    ## Never scouted; rendered as blank darkness. One-way -> EXPLORED, never reverts.
	EXPLORED,  ## Terrain/buildings remembered, no current intel on movement in this hex.
	VISIBLE,   ## An active vision source covers this hex right now; full real-time information.
}

enum DayPhase {
	DAY,    ## First half of TickManager's day cycle — baseline vision.
	NIGHT,  ## Second half — drives FogOfWarManager's vision contraction.
}

enum HordeState {
	WANDERING,  ## Default — drifts across passable uncleared wilderness, no deliberate target.
	ATTRACTED,  ## Pathing deliberately toward a noise/light source above threshold (NoiseManager).
	ATTACKING,  ## Besieging a specific wall segment/hex, handed off to combat.
}

## Three internal fidelity bands subdividing Tactical zoom (past
## CameraController.tactical_zoom_threshold) as the camera keeps zooming in
## toward max_zoom — Strategic view's own icon-based rendering
## (StrategicOverlayManager) is untouched by this and doesn't consult it.
## Meaningless outside Tactical zoom; every consumer (TacticalEntityLayer,
## TacticalHexView/LocalDetailManager) already gates on
## CameraController.is_tactical_zoom() before reading this.
enum TacticalFidelity {
	LOW,     ## Just past the Strategic/Tactical cut — simple silhouettes/blobs, shape-and-color differentiated enough to tell unit from building from zombie, no finer detail.
	MEDIUM,  ## Some discernible detail — a unit's role/tier reads at a glance, not yet individual-figure detail.
	HIGH,    ## Full detail — individual squad figures/zombies.
}

enum TechUnlockType {
	WALL_TIER,        ## Unlocks a wall tier (unlock_value: 1=Brick, 2=Concrete; tier 0/Wooden is baseline, no tech needed).
	UNIT_TIER,        ## Unlocks a whole unit tier, all 3 roles at once (unlock_value: 1-5; tier 0 is baseline, no tech needed).
	BUILDING_TIER,    ## Unlocks a whole building tier (unlock_value: 1-5; tier 0 is baseline, no tech needed) — see TechManager.is_building_tier_unlocked().
	BUILDING_VARIANT, ## Unlocks an advanced building variant — documented hook, unused until a variant building actually exists.
	SEAFARING,        ## The one node gated on campaign state as well as prerequisites — see TechDefinition.requires_wales_and_scotland_retaken.
}

## EventManager's typed event records — what kind of thing happened.
## COMBAT/TERRITORY/ECONOMY are raised today (see EventManager's own doc
## comment for every wired source); UNREST/NARRATIVE are documented, unused
## hooks for Discontent and a future CampaignManager — same "real gate,
## nothing calls it yet" convention as TechUnlockType.BUILDING_VARIANT above.
enum EventCategory {
	COMBAT,     ## A unit engaged, a building was ruined, or a wall segment breached (under-attack alerts).
	TERRITORY,  ## A district was lost to or recaptured from the horde.
	ECONOMY,    ## A resource stockpile ran dry, or food satisfaction dropped a band.
	UNREST,     ## Not yet raised — DiscontentManager has no "unrest event" concept of its own yet, only its existing production-penalty math.
	NARRATIVE,  ## Not yet raised — relic-site/Final Mystery beats; no CampaignManager exists yet to raise one.
}

## How urgently EventManager.raise_event() wants the player's attention.
## AlertManager auto-pauses on anything above INFO — see its own doc
## comment for why that's not as spammy as "pause on every WARNING" sounds.
enum EventSeverity {
	INFO,      ## Worth a toast, not worth stopping the clock — today's only source is a recaptured district.
	WARNING,   ## Notable: a unit took a hit and survived, food dipped under 100%, a resource stockpile hit zero.
	CRITICAL,  ## Severe: a unit/building destroyed, a wall breached, territory lost, a large horde spotted, the colony starving.
}
