class_name GameEnums
extends RefCounted

## Central namespace for shared enum vocabulary used across the game's systems.
## Kept as a single static reference (no instances, no autoload) so every
## script speaks the same terms without cross-importing each other directly.

enum BiomeType {
	URBAN,        ## City streets / settlement footprint.
	INDUSTRIAL,   ## Slag heaps, mine spoil, blighted factory ground.
	FARMLAND,     ## Open, tillable countryside (fertility varies, see SoilFertility).
	MOORLAND,     ## Open, less fertile countryside.
	HIGHLAND,     ## Elevated terrain / mountain chains (Pennines, Chilterns, Cotswolds).
	WATERWAY,     ## River or canal hex — fordable (Phase 2.12.1), unlike open OCEAN below.
	WETLAND,      ## Marsh, fen or peat bog.
	OCEAN,        ## Open sea (design doc, user request: "ensure our hex tile map is representative of the entire UK and Ireland") — impassable (HexCell.is_passable()) until Phase 7.5's Naval Logistics/ships exist; the map's own default base layer before BritishGeographyData's landmass stamp turns land hexes to MOORLAND.
	## Real-data granularity pass (user request, 2026-08-11): carved out of
	## what tools/geo_bake previously flattened into MOORLAND — OSM
	## `landuse=forest`/`natural=wood` (WOODLAND) and `natural=heath`/
	## `natural=scrub` (HEATHLAND) were already being fetched and discarded
	## into the same catch-all bucket as open grazing land. Appended at the
	## END of the enum, not inserted alphabetically/thematically near
	## MOORLAND/WETLAND above — Godot enums serialize as raw int ordinals
	## (HexCell.biome_type, SaveLoadManager) and inserting mid-list would
	## silently shift OCEAN's ordinal and corrupt any existing save file.
	WOODLAND,     ## Dense tree cover — OSM landuse=forest / natural=wood.
	HEATHLAND,    ## Heather/gorse scrubland — OSM natural=heath / natural=scrub.
}

enum SoilFertility {
	LUSH,        ## Prime farmland (e.g. Cheshire Plain, Midlands).
	POOR,        ## Marginal farmland (e.g. moorland fringe).
	DESOLATE,    ## Industrial blight or drained wetland; barely arable.
	NOT_ARABLE,  ## Urban, open water, etc. — farming is not applicable here.
}

enum DistrictType {
	URBAN_CENTER,          ## Civilian core: Town Halls, Churches, Telegraph Relays.
	INDUSTRIAL_ESTATE,     ## Production core: foundries, mills, workshops.
	UNCLEARED_WILDERNESS,  ## Contested ground; active zombie presence until cleared.
}

enum TerrainFeature {
	NONE,
	RIVER,
	CANAL,
	MARSH,
	PEAT_BOG,
	ESCARPMENT,  ## Mountain / hill chokepoint terrain.
}

enum CameraPerspective {
	TOP_DOWN,
	ISOMETRIC,
}

enum ResourceType {
	FOOD,                   ## Population upkeep drain.
	ENERGY,                 ## Coal, Gas, Oil used for Boiler/heating/streetlamp upkeep.
	GUNPOWDER,              ## Ranged combat & garrison upkeep.
	RESEARCH_POINTS,        ## Tech Tree progression currency (Phase 2.9) — generated by civic/knowledge buildings, spent by TechManager.
	WOOD,                   ## Construction material.
	BRICKS,                 ## Construction material.
	CAST_IRON,              ## Construction material.
	REINFORCED_CONCRETE,    ## Construction material — no Phase 2 building produces this yet.
}

enum BuildingCategory {
	HOUSING_CIVIL,       ## Terraced Tenements, Workhouses, Watchtowers, etc.
	INDUSTRY_EXTRACTION, ## Brickworks, kilns, pitheads, foundries, powder mills, ammo dumps.
	AGRICULTURE,         ## Tenant Farms, Grain Silos, Cattle Yards.
	DEFENSE_WORKS,       ## Phase 4.1: Searchlight Tower (a normal hex-placed building), plus Ditch/Oil Pit's cost data (placed via WallManager, not BuildingManager — see WallManager's own doc comment).
}

enum BuildingType {
	# --- Housing & Civil ---
	TERRACED_TENEMENT,
	WORKHOUSE,
	CHURCH_STEEPLE_WATCHTOWER,
	GAS_STREETLAMP,
	TELEGRAPH_RELAY_OFFICE,
	STEAM_PRINTING_PRESS,
	TOWN_HALL,   ## Not in the Phase 2.1 checklist by name, but required as a Civilian ZoC
	GARRISON,    ## projector by 2.3; added here as the civic-seat/militia-HQ pairing for it.
	# --- Industry & Extraction ---
	TIMBER_CAMP,  ## Added post-launch, economy-balance pass: the ONLY Wood producer in the whole tree — every other raw construction material (Bricks/Cast Iron/Gunpowder) already had a dedicated extractor, Wood never did (a real gap in the original Phase 2.1 checklist, not just an implementation slip — found by simulating a real opening and watching Wood run to zero with no way back up).
	CLAY_BRICKWORKS,
	CHARCOAL_KILN,
	COAL_PITHEAD,
	CAST_IRON_FOUNDRY,
	SALTPETRE_POWDER_MILL,
	FORWARD_AMMO_DUMP,
	# --- Agriculture ---
	TENANT_FARM,
	GRAIN_SILO,
	CATTLE_YARD,
	# --- Defense Works (Phase 4.1) ---
	SEARCHLIGHT_TOWER,  ## Normal hex-placed building (BuildingManager), like Gas Streetlamp.
	DITCH,              ## Cost data only — placed via WallManager.add_defense_work(), attached to a specific WallSegment.
	OIL_PIT,            ## Cost data only — same as DITCH.
}

## Design doc Phase 5.4: 3 roles per unit tier. Melee/ranged are
## self-explanatory; special's "exact combat identity per tier (area-effect,
## heavy-breach, mobility/scouting, etc.) is a balancing/design pass per
## unit, not fixed by this spec" (design doc, decided) — UnitCatalog gives
## each special-role unit a plausible baseline, not a final tuned identity.
enum UnitRole {
	MELEE,
	RANGED,
	SPECIAL,
}

## Design doc, user request: "each special unit type should do something
## special (indicated by the name)" — a real, mechanical differentiator for
## every SPECIAL-role unit, not just flavor text (until this pass all six
## shared one identical baseline stat curve — see UnitCatalog's own doc
## comment on that gap). NONE covers every MELEE/RANGED unit (their
## differentiation is the existing tier/role HP-damage curve alone) and any
## SPECIAL unit that hasn't been given a distinct mechanic.
enum UnitAbility {
	NONE,
	UNARMED_SCOUT,       ## Outrider — cannot fight (near-zero attack_damage), fast mounted vision/recon only. See UnitCatalog.
	MOUNTED_FIREARM,     ## Chasseur — mounted AND actually armed, a real combat option unlike the Outrider it out-classes. See UnitCatalog.
	EXPLOSIVE_SPLASH,    ## Grenadier — grenades; expressed as a real damage bonus (a horde is already one clustered "blob" target, so splash reads as extra effectiveness against it). See UnitCatalog.
	CHARGE_KNOCKBACK,    ## Dragoon — charging into a horde on contact knocks it back a hex AND stuns it briefly. See CombatCoordinator._apply_special_ability_effects().
	TRAMPLE_KNOCKBACK,   ## Traction Ram AND Holt Breaker — same knockback as a Charge, no stun, riding on a much larger HP pool (a damage sponge that shoves zombies aside rather than a fast shock unit); shared by both because they're the same "crush the horde by weight" identity at two tiers, not two different mechanics. See CombatCoordinator._apply_special_ability_effects().
	MOBILE_SUPPLY_DUMP,  ## Searchlight Tender — projects a small Military ZoC/resupply aura around wherever it currently stands, like a walking (much-reduced-radius) Forward Ammo Dump; doubles as a moving vision source too (FogOfWarManager reads ZoC coverage as vision), which is what actually "illuminates infected sectors" per its own description. See LogisticsNetwork.recompute().
	RAPID_RESPONSE,      ## Armoured Command Car — fast and lightly armed rather than a heavy hitter: real speed/damage/HP leans (UnitCatalog), no bespoke effect code, same "pure stat lean under a descriptive name" shape as UNARMED_SCOUT/MOUNTED_FIREARM/EXPLOSIVE_SPLASH.
}

## Design doc Phase 5.4's decided roster — 6 tiers (0-5) x 3 roles = 18
## units. Declared tier-by-tier, melee/ranged/special within each tier, same
## grouped-comment convention BuildingType uses.
enum UnitType {
	# --- Tier 0 (the "Free Ammo" starting tier, no tech needed) ---
	TRUNCHEONEER,           ## Melee.
	TOXOPHILITE,            ## Ranged — bow; no Gunpowder upkeep, exempt from the depletion penalty by design.
	OUTRIDER,               ## Special — scouting/mobility.
	# --- Tier 1 (unit_tier_1) ---
	NAVVY,                  ## Melee.
	YEOMAN_MARKSMAN,        ## Ranged — the first firearm-era ranged unit; Gunpowder depletion penalty starts here.
	GRENADIER,              ## Special.
	# --- Tier 2 (unit_tier_2) ---
	REDCOAT,                ## Melee.
	RIFLEMAN,               ## Ranged.
	CHASSEUR,               ## Special.
	# --- Tier 3 (unit_tier_3) ---
	HIGHLANDER,             ## Melee.
	SHARPSHOOTER,           ## Ranged.
	DRAGOON,                ## Special.
	# --- Tier 4 (unit_tier_4) — Early Mechanization & Heavy Logistics (1890s-1900s). ---
	TRACTION_RAM,           ## Melee.
	MAXIM_QUADRICYCLE,      ## Ranged.
	SEARCHLIGHT_TENDER,     ## Special.
	# --- Tier 5 (unit_tier_5) — Peak Industrial Warfare (1910s-1920s). ---
	HOLT_BREAKER,           ## Melee.
	FIELD_HOWITZER_GUN_TRACTOR,  ## Ranged.
	ARMOURED_COMMAND_CAR,   ## Special.
}

## Design doc Phase 5.6's "standard RTS order set" — what a UnitInstance is
## currently doing, driven by UnitOrderController. HOLD is the default (a
## freshly-trained unit with no rally point set just sits at its training
## building). ATTACK_MOVE is data-distinct from MOVE, but drives
## identically — CombatCoordinator (Phase 5.4/5.9/5.10's live combat
## trigger) engages a horde on contact regardless of a unit's current
## order, so there's no distinct "attack" behavior left for this value to
## carry beyond intent-tracking. See CombatCoordinator's own doc comment.
enum UnitOrderType {
	HOLD,         ## Stand fast at the current hex — the default.
	MOVE,         ## Path to move_target, one hex per movement tick, then reverts to HOLD on arrival.
	ATTACK_MOVE,  ## Same movement AND same on-contact engagement as MOVE — see this enum's own doc comment.
	PATROL,       ## Loop through patrol_waypoints indefinitely, one leg at a time.
	GARRISON,     ## Stand fast at the current hex, same as HOLD, but with two real payoffs HOLD doesn't get: Phase 2.5.4's healing (UnitOrderController._regen_if_friendly()) and Phase 4.1/5.6's incoming-damage reduction (CombatCoordinator._garrison_incoming_multiplier()), stacking further at night near a Searchlight Tower.
}

enum ZoneOfControlType {
	MILITARY,   ## Forward Ammo Dumps, Garrisons, Watchtowers, Combat Units.
	CIVILIAN,   ## Town Halls, Churches (the Watchtower's civilian half), Telegraph Relays.
}

enum SupplyLineType {
	ROAD,
	RAILWAY,
	CANAL,
}

enum PropType {
	TREE,
	BUSH,
	ROCK,
	REED,  ## Wetland/waterway fringe vegetation.
}

enum FogState {
	UNSEEN,    ## Never scouted; rendered as blank darkness. One-way -> EXPLORED, never reverts.
	EXPLORED,  ## Terrain/buildings remembered, no current intel on movement in this hex.
	VISIBLE,   ## An active vision source covers this hex right now; full real-time information.
}

enum DayPhase {
	DAY,    ## First half of TickManager's day cycle — baseline vision, no zombie/unit modifiers wired yet (Phase 5.2/5.4 don't exist).
	NIGHT,  ## Second half — drives FogOfWarManager's vision contraction (Phase 2.6.4); zombie/unit modifiers deferred the same way.
}

enum HordeState {
	WANDERING,  ## Default (design doc Phase 5.10) — drifts across passable uncleared wilderness, no deliberate target. The only state HordeManager actually produces right now.
	ATTRACTED,  ## Pathing deliberately toward a noise/light source above threshold. Not yet produced — needs Phase 5.2's industrial-noise tracking, which doesn't exist yet.
	ATTACKING,  ## Besieging a specific wall segment/hex, handed off to combat. Not yet produced — needs Phase 5.4's CombatEngine, which doesn't exist yet.
}

## Design doc Phase 2.5.5: three internal fidelity bands subdividing Tactical
## zoom (past `CameraController.tactical_zoom_threshold`) as the camera keeps
## zooming in toward `max_zoom` — Strategic view's own icon-based rendering
## (`StrategicOverlayManager`) is untouched by this and doesn't consult it.
## Meaningless outside Tactical zoom; every consumer (`TacticalEntityLayer`,
## `TacticalHexView`/`LocalDetailManager`) already gates on
## `CameraController.is_tactical_zoom()` before reading this, same as every
## other Tactical-only system.
enum TacticalFidelity {
	LOW,     ## Just past the Strategic/Tactical cut — simple silhouettes/blobs, shape-and-color differentiated enough to tell unit from building from zombie, no finer detail.
	MEDIUM,  ## Some discernible detail — a unit's role/tier reads at a glance, not yet individual-figure detail.
	HIGH,    ## Full detail — individual squad figures/zombies (Phase 2.5.4).
}

enum TechUnlockType {
	WALL_TIER,        ## Unlocks a Phase 4.1 wall tier (unlock_value: 1=Brick, 2=Concrete; tier 0/Wooden is baseline, no tech needed).
	UNIT_TIER,        ## Unlocks a whole Phase 5.4 unit tier, all 3 roles at once (unlock_value: 1-5; tier 0 is baseline, no tech needed).
	BUILDING_VARIANT, ## Unlocks an advanced building variant — documented hook, unused until a variant building actually exists.
	SEAFARING,        ## The one node gated on campaign state as well as prerequisites — see TechDefinition.requires_wales_and_scotland_retaken.
}

## Design doc Phase 6.2: EventManager's "typed event records" — what kind of
## thing happened. COMBAT/TERRITORY/ECONOMY are raised today (see
## EventManager's own doc comment for every wired source); UNREST/NARRATIVE
## are documented, unused hooks for Phase 2.11's Discontent and Phase 7.2's
## still-nonexistent CampaignManager — same "real gate, nothing calls it
## yet" convention as TechUnlockType.BUILDING_VARIANT above.
enum EventCategory {
	COMBAT,     ## A unit engaged, a building was ruined, or a wall segment breached (Phase 2.7.5's "under-attack" alerts).
	TERRITORY,  ## A district was lost to or recaptured from the horde (Phase 5.8).
	ECONOMY,    ## A resource stockpile ran dry, or food satisfaction dropped a band (Phase 2.2/2.10).
	UNREST,     ## Not yet raised — Phase 2.11's DiscontentManager has no "unrest event" concept of its own yet, only its existing production-penalty math.
	NARRATIVE,  ## Not yet raised — Phase 7.2's relic-site/Final Mystery beats; no CampaignManager exists yet to raise one.
}

## How urgently EventManager.raise_event() wants the player's attention.
## AlertManager (Phase 6.2) auto-pauses on anything above INFO — see its own
## doc comment for why that's not as spammy as "pause on every WARNING"
## sounds.
enum EventSeverity {
	INFO,      ## Worth a toast, not worth stopping the clock — today's only source is a recaptured district.
	WARNING,   ## Notable: a unit took a hit and survived, food dipped under 100%, a resource stockpile hit zero.
	CRITICAL,  ## Severe: a unit/building destroyed, a wall breached, territory lost, a large horde spotted, the colony starving.
}
